<?php

use yii\db\Schema;
use yii\db\Migration;

class m221129_064527_productDataInsert extends Migration
{

    public function init()
    {
        $this->db = 'db';
        parent::init();
    }

    public function safeUp()
    {
        $this->batchInsert('{{%product}}',
                           ["id", "category_id", "name", "content", "price", "keywords", "description", "img", "hit", "new", "sale"],
                            [
    [
        'id' => 1,
        'category_id' => 4,
        'name' => 'Кросовки 1',
        'content' => 'Супер кросовки 1',
        'price' => 10.0,
        'keywords' => null,
        'description' => null,
        'img' => 'product-1.png',
        'hit' => '0',
        'new' => '0',
        'sale' => '0',
    ],
    [
        'id' => 2,
        'category_id' => 4,
        'name' => 'Кросовки 2',
        'content' => 'Супер кросовки 2',
        'price' => 7.0,
        'keywords' => null,
        'description' => null,
        'img' => 'product-2.png',
        'hit' => '1',
        'new' => '1',
        'sale' => '0',
    ],
    [
        'id' => 3,
        'category_id' => 4,
        'name' => 'Кросовки 3',
        'content' => 'Супер кросовки 3',
        'price' => 15.0,
        'keywords' => null,
        'description' => null,
        'img' => 'product-3.png',
        'hit' => '0',
        'new' => '1',
        'sale' => '0',
    ],
    [
        'id' => 4,
        'category_id' => 4,
        'name' => 'Кросовки 4',
        'content' => 'Супер кросовки 4',
        'price' => 10.0,
        'keywords' => null,
        'description' => null,
        'img' => 'product-4.png',
        'hit' => '0',
        'new' => '0',
        'sale' => '1',
    ],
    [
        'id' => 5,
        'category_id' => 9,
        'name' => 'Одежда 1',
        'content' => 'Супер одежда 1',
        'price' => 20.0,
        'keywords' => null,
        'description' => null,
        'img' => 'product-5.jpg',
        'hit' => '0',
        'new' => '0',
        'sale' => '0',
    ],
    [
        'id' => 6,
        'category_id' => 9,
        'name' => 'Одежда 2',
        'content' => 'Супер одежда 2',
        'price' => 23.0,
        'keywords' => null,
        'description' => null,
        'img' => 'product-6.jpg',
        'hit' => '1',
        'new' => '0',
        'sale' => '0',
    ],
    [
        'id' => 7,
        'category_id' => 9,
        'name' => 'Одежда 3',
        'content' => 'Супер одежда 3',
        'price' => 25.0,
        'keywords' => null,
        'description' => null,
        'img' => 'product-7.jpg',
        'hit' => '1',
        'new' => '1',
        'sale' => '0',
    ],
    [
        'id' => 8,
        'category_id' => 9,
        'name' => 'Одежда 4',
        'content' => 'Супер одежда 4',
        'price' => 18.0,
        'keywords' => null,
        'description' => null,
        'img' => 'product-8.jpg',
        'hit' => '1',
        'new' => '0',
        'sale' => '1',
    ],
    [
        'id' => 9,
        'category_id' => 4,
        'name' => 'Кросовки 1',
        'content' => 'Супер кросовки 1',
        'price' => 10.0,
        'keywords' => null,
        'description' => null,
        'img' => 'product-1.png',
        'hit' => '0',
        'new' => '0',
        'sale' => '0',
    ],
    [
        'id' => 10,
        'category_id' => 4,
        'name' => 'Кросовки 2',
        'content' => 'Супер кросовки 2',
        'price' => 7.0,
        'keywords' => null,
        'description' => null,
        'img' => 'product-2.png',
        'hit' => '1',
        'new' => '1',
        'sale' => '0',
    ],
    [
        'id' => 11,
        'category_id' => 4,
        'name' => 'Кросовки 3',
        'content' => 'Супер кросовки 3',
        'price' => 15.0,
        'keywords' => null,
        'description' => null,
        'img' => 'product-3.png',
        'hit' => '0',
        'new' => '1',
        'sale' => '0',
    ],
    [
        'id' => 12,
        'category_id' => 4,
        'name' => 'Кросовки 4',
        'content' => 'Супер кросовки 4',
        'price' => 10.0,
        'keywords' => null,
        'description' => null,
        'img' => 'product-4.png',
        'hit' => '0',
        'new' => '0',
        'sale' => '1',
    ],
    [
        'id' => 13,
        'category_id' => 9,
        'name' => 'Одежда 1',
        'content' => 'Супер одежда 1',
        'price' => 20.0,
        'keywords' => null,
        'description' => null,
        'img' => 'product-5.jpg',
        'hit' => '0',
        'new' => '0',
        'sale' => '0',
    ],
    [
        'id' => 14,
        'category_id' => 9,
        'name' => 'Одежда 2',
        'content' => 'Супер одежда 2',
        'price' => 23.0,
        'keywords' => null,
        'description' => null,
        'img' => 'product-6.jpg',
        'hit' => '1',
        'new' => '0',
        'sale' => '0',
    ],
    [
        'id' => 15,
        'category_id' => 9,
        'name' => 'Одежда 3',
        'content' => 'Супер одежда 3',
        'price' => 25.0,
        'keywords' => null,
        'description' => null,
        'img' => 'product-7.jpg',
        'hit' => '1',
        'new' => '1',
        'sale' => '0',
    ],
    [
        'id' => 16,
        'category_id' => 9,
        'name' => 'Одежда 4',
        'content' => 'Супер одежда 4',
        'price' => 18.0,
        'keywords' => null,
        'description' => null,
        'img' => 'product-8.jpg',
        'hit' => '1',
        'new' => '0',
        'sale' => '1',
    ],
]
        );
    }

    public function safeDown()
    {
        //$this->truncateTable('{{%product}} CASCADE');
    }
}
